export interface CandidateSeedRecord {
    title: string;
    first_name: string;
    last_name: string;
    number: number;
    image_url: string;
    party_id: number;
    constituency_id: number;
    created_at: Date;
}

export const candidateSeedData: CandidateSeedRecord[] = [
    // Bangkok Constituency 1 - 4 candidates
    {
        title: 'Mr.',
        first_name: 'Somchai',
        last_name: 'Jiravantana',
        number: 1,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-1.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0xLmpwZyIsImlhdCI6MTc3NDY0NTU3OCwiZXhwIjoxODA2MTgxNTc4fQ.zblYs4LRDPVkhEGVua_o_x81xvevSNcWFNgW1VLJq6E',
        party_id: 1,
        constituency_id: 1,
        created_at: new Date('2025-09-01T09:00:00Z'),
    },
    {
        title: 'Mr.',
        first_name: 'Niran',
        last_name: 'Suwannapong',
        number: 2,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-10.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0xMC5qcGciLCJpYXQiOjE3NzQ2NDU2MzQsImV4cCI6MTgwNjE4MTYzNH0.eHAtlfGGpGNYc9AQuq8gxljIwvw7bQurmocpxx65OY0',
        party_id: 2,
        constituency_id: 1,
        created_at: new Date('2025-09-01T10:00:00Z'),
    },
    {
        title: 'Ms.',
        first_name: 'Pranee',
        last_name: 'Kaewbuasai',
        number: 3,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-11.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0xMS5qcGciLCJpYXQiOjE3NzQ2NDU2NDEsImV4cCI6MTgwNjE4MTY0MX0.05JPSheVvhC43Aa8WxS_v9mmrwgfyPCdd1l-vHcYiEc',
        party_id: 3,
        constituency_id: 1,
        created_at: new Date('2025-09-01T11:00:00Z'),
    },
    {
        title: 'Mr.',
        first_name: 'Anand',
        last_name: 'Ramnoi',
        number: 4,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-12.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0xMi5qcGciLCJpYXQiOjE3NzQ2NDU2NDgsImV4cCI6MTgwNjE4MTY0OH0.EXzSCaFQt74KNM2fLwHUpcYPZT-_2XfYW4hilTW9-VU',
        party_id: 4,
        constituency_id: 1,
        created_at: new Date('2025-09-01T12:00:00Z'),
    },

    // Bangkok Constituency 2 - 4 candidates
    {
        title: 'Mr.',
        first_name: 'Wanchai',
        last_name: 'Jittapong',
        number: 1,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-13.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0xMy5qcGciLCJpYXQiOjE3NzQ2NDU2NTQsImV4cCI6MTgwNjE4MTY1NH0.JSAGzrqoBpL3H3gd1ClDZF6DQM0rJt8blfpoCmPaYp4',
        party_id: 2,
        constituency_id: 2,
        created_at: new Date('2025-09-02T09:00:00Z'),
    },
    {
        title: 'Ms.',
        first_name: 'Siriporn',
        last_name: 'Nakornpol',
        number: 2,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-13.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0xMy5qcGciLCJpYXQiOjE3NzQ2NDU2NjIsImV4cCI6MTgwNjE4MTY2Mn0.Bn8LCfGq1-XQDEkE2yhtl27-k9kx4FGkOx6iJrbocDY',
        party_id: 1,
        constituency_id: 2,
        created_at: new Date('2025-09-02T10:00:00Z'),
    },
    {
        title: 'Mr.',
        first_name: 'Teerawat',
        last_name: 'Mingkwan',
        number: 3,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-14.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0xNC5qcGciLCJpYXQiOjE3NzQ2NDU2NjgsImV4cCI6MTgwNjE4MTY2OH0.1TkOXginL2aJxH44-vQRwA9UZ1bPPtis3QT6WIdx03w',
        party_id: 3,
        constituency_id: 2,
        created_at: new Date('2025-09-02T11:00:00Z'),
    },
    {
        title: 'Ms.',
        first_name: 'Nattaya',
        last_name: 'Ruamsuk',
        number: 4,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-15.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0xNS5qcGciLCJpYXQiOjE3NzQ2NDU2NzMsImV4cCI6MTgwNjE4MTY3M30.obiBHWRREmPiniA4yX1iNUmz0w2mRC8Zl2UEaWqxIIE',
        party_id: 5,
        constituency_id: 2,
        created_at: new Date('2025-09-02T12:00:00Z'),
    },

    // Bangkok Constituency 3 (CLOSED) - 4 candidates
    {
        title: 'Mr.',
        first_name: 'Pradit',
        last_name: 'Sangkot',
        number: 1,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-16.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0xNi5qcGciLCJpYXQiOjE3NzQ2NDU2ODEsImV4cCI6MTgwNjE4MTY4MX0.r8B0lwhDKhgyW89Kr44EL0clAy5fzTh9L2hW5YHDyo0',
        party_id: 1,
        constituency_id: 3,
        created_at: new Date('2025-09-03T09:00:00Z'),
    },
    {
        title: 'Mr.',
        first_name: 'Suphat',
        last_name: 'Kamang',
        number: 2,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-17.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0xNy5qcGciLCJpYXQiOjE3NzQ2NDU2ODYsImV4cCI6MTgwNjE4MTY4Nn0.5tzwonlgC25d4N3yic30qjcgUWx7HzNUyPwWHIew0mg',
        party_id: 2,
        constituency_id: 3,
        created_at: new Date('2025-09-03T10:00:00Z'),
    },
    {
        title: 'Ms.',
        first_name: 'Janya',
        last_name: 'Thepsan',
        number: 3,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-18.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0xOC5qcGciLCJpYXQiOjE3NzQ2NDU2OTIsImV4cCI6MTgwNjE4MTY5Mn0.3MpPKsR4nSNQvs-tGOks9JjPy93nDQaK0XKMyrDU8Tk',
        party_id: 3,
        constituency_id: 3,
        created_at: new Date('2025-09-03T11:00:00Z'),
    },
    {
        title: 'Mr.',
        first_name: 'Kitti',
        last_name: 'Phongsai',
        number: 4,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-19.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0xOS5qcGciLCJpYXQiOjE3NzQ2NDU2OTcsImV4cCI6MTgwNjE4MTY5N30._PEawDtY1ygOzb4e_1NMk0S_s8Jtj-MySnKihm7eKZY',
        party_id: 4,
        constituency_id: 3,
        created_at: new Date('2025-09-03T12:00:00Z'),
    },

    // Chiang Mai Constituency 1 - 4 candidates
    {
        title: 'Mr.',
        first_name: 'Damrong',
        last_name: 'Muangthai',
        number: 1,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-2.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0yLmpwZyIsImlhdCI6MTc3NDY0NTcwNCwiZXhwIjoxODA2MTgxNzA0fQ.ODW43ksHN0IeDEsDdNLPzkm3_jSTtXqXh5aKQS2Qceo',
        party_id: 3,
        constituency_id: 4,
        created_at: new Date('2025-09-04T09:00:00Z'),
    },
    {
        title: 'Mr.',
        first_name: 'Sarit',
        last_name: 'Jitmala',
        number: 2,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-20.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0yMC5qcGciLCJpYXQiOjE3NzQ2NDU3MDksImV4cCI6MTgwNjE4MTcwOX0.zyuKU6gcBqGOqqLkTqH05iwe9fHfOwG9yv9LWW-hL04',
        party_id: 1,
        constituency_id: 4,
        created_at: new Date('2025-09-04T10:00:00Z'),
    },
    {
        title: 'Ms.',
        first_name: 'Oranuch',
        last_name: 'Chaiwasin',
        number: 3,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-21.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0yMS5qcGciLCJpYXQiOjE3NzQ2NDU3MTksImV4cCI6MTgwNjE4MTcxOX0.SZQgAUnGycJ3uNteKASMqC5PK1iI5Yg9JdBxXGeUFvE',
        party_id: 2,
        constituency_id: 4,
        created_at: new Date('2025-09-04T11:00:00Z'),
    },
    {
        title: 'Mr.',
        first_name: 'Somkiat',
        last_name: 'Napaksin',
        number: 4,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-21.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0yMS5qcGciLCJpYXQiOjE3NzQ2NDU3MjUsImV4cCI6MTgwNjE4MTcyNX0.JJrTzaU9iGcyON8KkbU0OhZBRJvX6x_jv1uBxYPY5po',
        party_id: 5,
        constituency_id: 4,
        created_at: new Date('2025-09-04T12:00:00Z'),
    },

    // Chiang Mai Constituency 2 (CLOSED) - 4 candidates
    {
        title: 'Mr.',
        first_name: 'Visut',
        last_name: 'Kasemsan',
        number: 1,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-22.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0yMi5qcGciLCJpYXQiOjE3NzQ2NDU3MzAsImV4cCI6MTgwNjE4MTczMH0.DRUOl9bWPMI8KRa2vErsO-DWXJzsuChtl6zfiWnetFY',
        party_id: 2,
        constituency_id: 5,
        created_at: new Date('2025-09-05T09:00:00Z'),
    },
    {
        title: 'Ms.',
        first_name: 'Duangchai',
        last_name: 'Phatthanarak',
        number: 2,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-23.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0yMy5qcGciLCJpYXQiOjE3NzQ2NDU3MzUsImV4cCI6MTgwNjE4MTczNX0.rxyIlyTOHYQ9BitoIFrEHzNzjS3ERis2oqWlrP7Wsm8',
        party_id: 1,
        constituency_id: 5,
        created_at: new Date('2025-09-05T10:00:00Z'),
    },
    {
        title: 'Mr.',
        first_name: 'Pairoj',
        last_name: 'Sukjarit',
        number: 3,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-24.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0yNC5qcGciLCJpYXQiOjE3NzQ2NDU3NDAsImV4cCI6MTgwNjE4MTc0MH0.VtswkuSSdfOwTcusbFhhdMumTBzwnsCR29AlqLoalrs',
        party_id: 3,
        constituency_id: 5,
        created_at: new Date('2025-09-05T11:00:00Z'),
    },
    {
        title: 'Ms.',
        first_name: 'Kannika',
        last_name: 'Thammavong',
        number: 4,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-25.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0yNS5qcGciLCJpYXQiOjE3NzQ2NDU3NzEsImV4cCI6MTgwNjE4MTc3MX0.imw_un6_Okn9OhM7niY-pIatbh72t57EnMWREnZVTaY',
        party_id: 4,
        constituency_id: 5,
        created_at: new Date('2025-09-05T12:00:00Z'),
    },

    // Phuket Constituency 1 - 4 candidates
    {
        title: 'Mr.',
        first_name: 'Prawit',
        last_name: 'Khaimuk',
        number: 1,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-26.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0yNi5qcGciLCJpYXQiOjE3NzQ2NDU3ODAsImV4cCI6MTgwNjE4MTc4MH0.V6IGoJdkZ0GutMBLcvZgssSUGi7eqwqjLG3GnDiUiuk',
        party_id: 4,
        constituency_id: 6,
        created_at: new Date('2025-09-06T09:00:00Z'),
    },
    {
        title: 'Mr.',
        first_name: 'Sasithorn',
        last_name: 'Namchoo',
        number: 2,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-27.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0yNy5qcGciLCJpYXQiOjE3NzQ2NDU3ODksImV4cCI6MTgwNjE4MTc4OX0.9mE3bDKda-6CxxDGpDI3k3S1dAucddB-QOmizoMfT8E',
        party_id: 2,
        constituency_id: 6,
        created_at: new Date('2025-09-06T10:00:00Z'),
    },
    {
        title: 'Ms.',
        first_name: 'Issara',
        last_name: 'Namkong',
        number: 3,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-28.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0yOC5qcGciLCJpYXQiOjE3NzQ2NDU3OTUsImV4cCI6MTgwNjE4MTc5NX0.1W765pMhJu7kMcOuyPMSbIIj4D-FXVrtpbIdhD4BsMw',
        party_id: 1,
        constituency_id: 6,
        created_at: new Date('2025-09-06T11:00:00Z'),
    },
    {
        title: 'Mr.',
        first_name: 'Khanit',
        last_name: 'Saithong',
        number: 4,
        image_url: 'https://qqoywnidyqyoqjalvcpu.supabase.co/storage/v1/object/sign/election-bucket/candidates/Image-28.jpg?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MmNlZmY0Mi1iZjdkLTQzMDMtOTA0Ny01MjQwYThjMDJmNDgiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJlbGVjdGlvbi1idWNrZXQvY2FuZGlkYXRlcy9JbWFnZS0yOC5qcGciLCJpYXQiOjE3NzQ2NDU4MzQsImV4cCI6MTgwNjE4MTgzNH0.UaUeua9l5Ru52r5Alxb31F16btToPSm76k6yb61XEt8',
        party_id: 5,
        constituency_id: 6,
        created_at: new Date('2025-09-06T12:00:00Z'),
    },
];